install.packages(c("formatR", "Rcpp", "RcppArmadillo", "RcppEigen", "Matrix", "R.utils", "RColorBrewer", "hdf5r", "alluvial", "optparse", "aws.s3", "aws.signature", "cellranger", "ClusterR", "ColorPalette", "colorRamps", "colorscience", "colorspace", "colourpicker", "corrplot", "d3heatmap", "d3Network", "dbplyr", "doMC", "doParallel", "doRNG", "doSNOW", "dplyr", "entropy", "eulerr", "future", "future.apply", "ggplotify", "ggpubr", "ggrepel", "ggsci", "ggseqlogo", "ggstatsplot", "ggthemes", "glasso", "glmnet", "gProfileR", "gprofiler2", "harmonicmeanp", "heatmap.plus", "heatmap3", "heatmaply", "hunspell", "igraph", "knitr", "leiden", "MASS", "Matrix.utils", "matrixStats", "mcmc", "networkD3", "nnls", "openxlsx", "philentropy", "plot3D", "plotly", "pROC", "progress", "purrr", "R2HTML", "R6", "RcppAnnoy", "RcppHNSW", "RcppParallel", "RcppProgress", "RCurl", "readr", "rmarkdown", "rmdformats", "ROCR", "RSQLite", "rstantools", "rstudioapi", "rsvd", "Rtsne", "SNFtool", "snow", "SuperExactTest", "threejs", "tibble", "tidygraph", "tidyr", "tidyselect", "tidytree", "UpSetR", "viridis", "visNetwork", "WGCNA", "wordcloud", "metap", "Seurat", "ineq", "pals", "seriation"))
BiocManager::install(c("SingleCellExperiment", "monocle", "ComplexHeatmap", "RRHO", "MAST", "biomaRt", "clusterProfiler", "DESeq", "DESeq2", "DO.db", "DOSE", "edgeR", "EnhancedVolcano", "enrichplot", "ensembldb", "fgsea", "ggpubr", "GOsummaries", "Gviz", "limma", "RCy3", "reactome.db", "ReactomePA", "Rgraphviz", "RUVnormalize", "RUVnormalizeData", "schex", "seqLogo", "seqPattern", "sva", "TFBSTools", "topGO", "pachterlab/sleuth", "SummarizedExperiment", "scran", "scater", "batchelor", "slingshot", "clusterExperiment", "DropletUtils"))

devtools::install_github("slowkow/mhg")
devtools::install_github("immunogenomics/presto")
devtools::install_github("jlmelville/uwot")
devtools::install_github("immunogenomics/harmony")
devtools::install_github("MacoskoLab/liger")
devtools::install_github("shmohammadi86/SCINET")
devtools::install_github("shmohammadi86/NetLibR")
devtools::install_github("shmohammadi86/ACTIONet", "R-release")
