name: base
channels:
  - conda-forge
  - pytorch
  - bioconda
  - defaults
dependencies:
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - pandas
  - pyyaml
  - cwltool
  - plotly
  - kb-python
  - cellxgene
  - anndata
  - scanpy
  - scvi-tools
  - pip
  - pip:
    - scrublet
    - solo-sc
